services:
  - type: web
    name: medical-crm
    env: python
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt && 
      python -c "from sqlalchemy import create_engine; from app.core.config import settings; engine = create_engine(settings.DATABASE_URL); engine.execute('DROP TABLE IF EXISTS alembic_version')" || true &&
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medical-crm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: medical-crm-db
    databaseName: medical_crm
    plan: free