"""create_leads_table

Revision ID: d39087f423d4
Revises: 
Create Date: 2025-02-17 18:17:25

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from app.db.models.lead import LeadStatus

# revision identifiers, used by Alembic.
revision = 'd39087f423d4'  # Cambiado al ID que está buscando
down_revision = None  # Primera migración, no tiene migración anterior
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('status', sa.Enum(LeadStatus), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###