"""create_leads_table

Revision ID: create_leads_table
Revises: 
Create Date: 2025-02-01 15:18:57

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from app.db.models.lead import LeadStatus

# revision identifiers, used by Alembic.
revision = 'create_leads_table_20250201'
down_revision = None  # Cambiado de '98cce90aab5c' a None porque es la primera migración
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('status', sa.Enum(LeadStatus), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###