"""add_leads_table

Revision ID: 93a273b1117b
Revises: 98cce90aab5c
Create Date: 2025-02-01 12:08:19.086832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a273b1117b'
down_revision = '98cce90aab5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###