"""add_leads_table

Revision ID: d39087f423d4
Revises: 93a273b1117b
Create Date: 2025-02-01 12:13:57.435209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39087f423d4'
down_revision = '93a273b1117b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###