"""add_updated_at_to_appointments

Revision ID: fd1b96bc7d53
Revises: ce94d1a0e5f0
Create Date: 2025-01-25 12:37:33.517585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1b96bc7d53'
down_revision: Union[str, None] = 'ce94d1a0e5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
